@startuml
left to right direction
actor "Kepala Program Studi" as Kaprodi
actor "Dosen" as Dosen
actor "Mahasiswa" as Mahasiswa
actor "Admin" as Admin

rectangle "Modul Kurikulum dan Ketentuan OBE" {
  usecase "Mengelola Mata Kuliah" as UC1
  usecase "Mengelola Kurikulum Prodi" as UC2
  usecase "Mengelola Template Evaluasi" as UC3
  usecase "Mengelola Manajemen Capaian" as UC4
  usecase "Mengatur Grup MK Wajib/Pilihan" as UC5
  usecase "Mengelola Tahun Kurikulum" as UC6
  usecase "Melihat Laporan Monitoring OBE" as UC7
}

Kaprodi -- UC1
Kaprodi -- UC2
Kaprodi -- UC3
Kaprodi -- UC4
Kaprodi -- UC5
Kaprodi -- UC6
Kaprodi -- UC7

Admin ..> (UC1)
Dosen ..> (UC3)
Dosen ..> (UC4)
Mahasiswa ..> (UC7)

usecase "Autentikasi SSO Login" as Auth
UC1 ..> Auth : <<include>>
UC2 ..> Auth : <<include>>
UC3 ..> Auth : <<include>>
UC4 ..> Auth : <<include>>
UC5 ..> Auth : <<include>>
UC6 ..> Auth : <<include>>
UC7 ..> Auth : <<include>>

@enduml